#!/usr/bin/env bash
set -euo pipefail

expand_tilde() {
  local value="$1"
  case "$value" in
    "~") printf '%s\n' "$HOME" ;;
    "~/"*) printf '%s\n' "$HOME/${value#"~/"}" ;;
    *) printf '%s\n' "$value" ;;
  esac
}

ROOT_PROJECT="${ROOT_PROJECT:-$HOME/src/xr_tracking}"
ROOT_PROJECT="$(expand_tilde "$ROOT_PROJECT")"

IMU_3DOF_BACKEND_BIN="${IMU_3DOF_BACKEND_BIN:-$ROOT_PROJECT/bin/backends/imu_3dof/imu_3dof_backend}"
IMU_3DOF_BACKEND_BIN="$(expand_tilde "$IMU_3DOF_BACKEND_BIN")"

TRANSPORT="${IMU_3DOF_TRANSPORT:-${TRANSPORT:-shm}}"
CAPTURE_REGISTRY="${CAPTURE_REGISTRY:-/tmp/capture_service_streams.json}"
IMU_STREAM="${IMU_STREAM:-imu0}"
CAM0_STREAM="${CAM0_STREAM:-camera0}"
CAM1_STREAM="${CAM1_STREAM:-camera1}"
CAPTURE_TCP_HOST="${CAPTURE_TCP_HOST:-127.0.0.1}"
CAPTURE_TCP_PORT="${CAPTURE_TCP_PORT:-45660}"

POSE_REGISTRY="${POSE_REGISTRY:-${TRACKING_REGISTRY:-/tmp/tracking_streams.json}}"
POSE_STREAM="${POSE_STREAM:-hmd_pose_3dof}"
POSE_SHM_NAME="${POSE_SHM_NAME:-track_hmd_pose_3dof}"
POSE_FRAME="${POSE_FRAME:-tracking_world}"
POSE_SLOTS="${POSE_SLOTS:-1024}"

CONTROL_FILE="${XR_BACKEND_CONTROL_FILE:-/tmp/xr_backend_control.json}"
PRINT_EVERY="${PRINT_EVERY:-250}"
DURATION="${DURATION:-0}"

GRAVITY_MAGNITUDE="${GRAVITY_MAGNITUDE:-9.80665}"
IMU_3DOF_ACCEL_CORRECTION_GAIN="${IMU_3DOF_ACCEL_CORRECTION_GAIN:-0.0}"
IMU_3DOF_GYRO_BIAS_GAIN="${IMU_3DOF_GYRO_BIAS_GAIN:-0.0005}"
IMU_3DOF_ACCEL_TRUST_MIN="${IMU_3DOF_ACCEL_TRUST_MIN:-7.0}"
IMU_3DOF_ACCEL_TRUST_MAX="${IMU_3DOF_ACCEL_TRUST_MAX:-12.5}"
IMU_3DOF_MAX_DT_MS="${IMU_3DOF_MAX_DT_MS:-30.0}"
IMU_3DOF_INITIAL_ACCEL_ALIGN="${IMU_3DOF_INITIAL_ACCEL_ALIGN:-1}"
IMU_3DOF_INITIAL_RECENTER="${IMU_3DOF_INITIAL_RECENTER:-1}"
IMU_3DOF_RECENTER_FULL_ORIENTATION="${IMU_3DOF_RECENTER_FULL_ORIENTATION:-1}"
IMU_3DOF_STARTUP_WARMUP_MS="${IMU_3DOF_STARTUP_WARMUP_MS:-800.0}"
IMU_3DOF_STARTUP_MIN_SAMPLES="${IMU_3DOF_STARTUP_MIN_SAMPLES:-200}"
IMU_3DOF_STARTUP_GYRO_BIAS_MAX_RAD_S="${IMU_3DOF_STARTUP_GYRO_BIAS_MAX_RAD_S:-0.08}"
IMU_3DOF_STARTUP_RECENTER_SETTLE_MS="${IMU_3DOF_STARTUP_RECENTER_SETTLE_MS:-0.0}"
IMU_3DOF_STARTUP_RECENTER_SETTLE_GYRO_MAX_RAD_S="${IMU_3DOF_STARTUP_RECENTER_SETTLE_GYRO_MAX_RAD_S:-0.12}"
IMU_3DOF_STATIONARY_GYRO_BIAS_GAIN="${IMU_3DOF_STATIONARY_GYRO_BIAS_GAIN:-0.75}"
IMU_3DOF_STATIONARY_GYRO_NORM_RAD_S="${IMU_3DOF_STATIONARY_GYRO_NORM_RAD_S:-0.06}"
IMU_3DOF_GYRO_DEADBAND_RAD_S="${IMU_3DOF_GYRO_DEADBAND_RAD_S:-0.008}"

[[ -x "$IMU_3DOF_BACKEND_BIN" ]] || {
  echo "[ERROR] imu_3dof_backend binary not found: $IMU_3DOF_BACKEND_BIN" >&2
  echo "[ERROR] Run: $ROOT_PROJECT/backends/imu_3dof/scripts/linux/install_imu_3dof.sh" >&2
  exit 1
}

args=(
  --transport "$TRANSPORT"
  --registry "$CAPTURE_REGISTRY"
  --imu-stream "$IMU_STREAM"
  --cam0-stream "$CAM0_STREAM"
  --cam1-stream "$CAM1_STREAM"
  --tcp-host "$CAPTURE_TCP_HOST"
  --tcp-port "$CAPTURE_TCP_PORT"
  --pose-registry "$POSE_REGISTRY"
  --pose-stream "$POSE_STREAM"
  --pose-shm-name "$POSE_SHM_NAME"
  --pose-frame "$POSE_FRAME"
  --pose-slots "$POSE_SLOTS"
  --control-file "$CONTROL_FILE"
  --gravity-magnitude "$GRAVITY_MAGNITUDE"
  --accel-correction-gain "$IMU_3DOF_ACCEL_CORRECTION_GAIN"
  --gyro-bias-gain "$IMU_3DOF_GYRO_BIAS_GAIN"
  --accel-trust-min "$IMU_3DOF_ACCEL_TRUST_MIN"
  --accel-trust-max "$IMU_3DOF_ACCEL_TRUST_MAX"
  --max-dt-ms "$IMU_3DOF_MAX_DT_MS"
  --initial-accel-align "$IMU_3DOF_INITIAL_ACCEL_ALIGN"
  --initial-recenter "$IMU_3DOF_INITIAL_RECENTER"
  --recenter-full-orientation "$IMU_3DOF_RECENTER_FULL_ORIENTATION"
  --startup-warmup-ms "$IMU_3DOF_STARTUP_WARMUP_MS"
  --startup-min-samples "$IMU_3DOF_STARTUP_MIN_SAMPLES"
  --startup-gyro-bias-max-rad-s "$IMU_3DOF_STARTUP_GYRO_BIAS_MAX_RAD_S"
  --startup-recenter-settle-ms "$IMU_3DOF_STARTUP_RECENTER_SETTLE_MS"
  --startup-recenter-settle-gyro-max-rad-s "$IMU_3DOF_STARTUP_RECENTER_SETTLE_GYRO_MAX_RAD_S"
  --stationary-gyro-bias-gain "$IMU_3DOF_STATIONARY_GYRO_BIAS_GAIN"
  --stationary-gyro-norm-rad-s "$IMU_3DOF_STATIONARY_GYRO_NORM_RAD_S"
  --gyro-deadband-rad-s "$IMU_3DOF_GYRO_DEADBAND_RAD_S"
  --print-every "$PRINT_EVERY"
  --duration "$DURATION"
)

cat <<EOF2
ROOT_PROJECT=$ROOT_PROJECT
IMU_3DOF_BACKEND_BIN=$IMU_3DOF_BACKEND_BIN
TRANSPORT=$TRANSPORT
CAPTURE_REGISTRY=$CAPTURE_REGISTRY
IMU_STREAM=$IMU_STREAM
POSE_REGISTRY=$POSE_REGISTRY
POSE_STREAM=$POSE_STREAM
POSE_SHM_NAME=$POSE_SHM_NAME
CONTROL_FILE=$CONTROL_FILE
EOF2

exec "$IMU_3DOF_BACKEND_BIN" "${args[@]}" "$@"
