#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

set -euo pipefail

expand_tilde() {
  local value="$1"
  case "$value" in
    "~") printf '%s\n' "$HOME" ;;
    "~/"*) printf '%s\n' "$HOME/${value#"~/"}" ;;
    *) printf '%s\n' "$value" ;;
  esac
}

XR_CALIB_COMMON_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XR_CALIB_COMMON_DIR="$(cd "$XR_CALIB_COMMON_SCRIPT_DIR/.." && pwd)"
XR_CALIBRATION_ROOT="$(cd "$XR_CALIB_COMMON_DIR/../.." && pwd)"
ROOT_PROJECT="${ROOT_PROJECT:-$(cd "$XR_CALIBRATION_ROOT/.." && pwd)}"
ROOT_PROJECT="$(expand_tilde "$ROOT_PROJECT")"

CALIB_TARGET="${CALIB_TARGET:-xreal_ultra}"
TARGET_PROFILE="${TARGET_PROFILE:-$XR_CALIB_COMMON_DIR/profiles/$CALIB_TARGET.env}"
TARGET_PROFILE="$(expand_tilde "$TARGET_PROFILE")"

if [[ ! -f "$TARGET_PROFILE" ]]; then
  echo "[calibration][ERROR] target profile not found: $TARGET_PROFILE" >&2
  echo "[calibration][ERROR] available targets:" >&2
  find "$XR_CALIB_COMMON_DIR/profiles" -maxdepth 1 -type f -name '*.env' -printf '  %f\n' 2>/dev/null | sed 's/\.env$//' >&2 || true
  exit 1
fi

# shellcheck source=/dev/null
source "$TARGET_PROFILE"

CALIB_TARGET_NAME="${CALIB_TARGET_NAME:-$CALIB_TARGET}"
CALIB_LABEL="${CALIB_LABEL:-$CALIB_TARGET_NAME}"
CALIB_DEVICE_NAME="${CALIB_DEVICE_NAME:-$CALIB_TARGET_NAME}"
CALIB_UNIT_ID="${CALIB_UNIT_ID:-default}"
CALIB_PROFILE_NAME="${CALIB_PROFILE_NAME:-default}"

CALIB_WORK_DIR="$(expand_tilde "${CALIB_WORK_DIR:-$HOME/xr_calib/$CALIB_TARGET_NAME}")"
RECORDS_DIR="$(expand_tilde "${RECORDS_DIR:-$HOME/xr_records/$CALIB_TARGET_NAME}")"
BAGS_DIR="$(expand_tilde "${BAGS_DIR:-$CALIB_WORK_DIR/bags}")"
TARGETS_DIR="$(expand_tilde "${TARGETS_DIR:-$CALIB_WORK_DIR/targets}")"
KALIBR_RUNS_DIR="$(expand_tilde "${KALIBR_RUNS_DIR:-$CALIB_WORK_DIR/kalibr_runs}")"
CAMERA_PROFILE_DIR="$(expand_tilde "${CAMERA_PROFILE_DIR:-$CALIB_WORK_DIR/camera/$CALIB_PROFILE_NAME}")"
FINAL_PROFILE_DIR="$(expand_tilde "${FINAL_PROFILE_DIR:-$CALIB_WORK_DIR/final/$CALIB_DEVICE_NAME/$CALIB_UNIT_ID/$CALIB_PROFILE_NAME}")"

PACKAGE_ROOT="$(expand_tilde "${PACKAGE_ROOT:-$ROOT_PROJECT/out/xr-gate}")"
CAPTURE_START_SCRIPT="$(expand_tilde "${CAPTURE_START_SCRIPT:-$PACKAGE_ROOT/bin/scripts/capture_service_cpp/start_capture_service_cpp.sh}")"
CAPTURE_CONFIG="$(expand_tilde "${CAPTURE_CONFIG:-}")"
CAPTURE_CONFIG_CAMERA_ONLY="$(expand_tilde "${CAPTURE_CONFIG_CAMERA_ONLY:-$CAPTURE_CONFIG}")"
CAPTURE_CONFIG_STEREO_IMU="$(expand_tilde "${CAPTURE_CONFIG_STEREO_IMU:-$CAPTURE_CONFIG}")"

CONVERTER_TO_BAG="$(expand_tilde "${CONVERTER_TO_BAG:-$XR_CALIB_COMMON_DIR/convert_unified_dataset_to_kalibr_bag.py}")"
CONVERTER_TO_RUNTIME="$(expand_tilde "${CONVERTER_TO_RUNTIME:-$XR_CALIB_COMMON_DIR/kalibr_to_basalt_unified_json.py}")"
RECORDER="$(expand_tilde "${RECORDER:-$XR_CALIB_COMMON_DIR/record_unified_kalibr_dataset.py}")"
BASALT_VIO_CONFIG_TEMPLATE="$(expand_tilde "${BASALT_VIO_CONFIG_TEMPLATE:-$XR_CALIB_COMMON_DIR/templates/basalt_vio_config_default.json}")"
BASALT_VIO_CONFIG_NAME="${BASALT_VIO_CONFIG_NAME:-basalt_vio_config_${CALIB_PROFILE_NAME}.json}"

DOCKER_IMAGE="${DOCKER_IMAGE:-kalibr-xr-gate:latest}"
ROS_SETUP="${ROS_SETUP:-/kalibr/catkin_ws/devel/setup.bash}"
APRILGRID_NAME="${APRILGRID_NAME:-aprilgrid_a4_5x7_25mm.yaml}"
APRILGRID_PATH="$(expand_tilde "${APRILGRID_PATH:-$TARGETS_DIR/$APRILGRID_NAME}")"
IMU_YAML_NAME="${IMU_YAML_NAME:-imu.yaml}"
IMU_YAML_PATH="$(expand_tilde "${IMU_YAML_PATH:-$CALIB_WORK_DIR/$IMU_YAML_NAME}")"

CAM0_TOPIC="${CAM0_TOPIC:-/cam0/image_raw}"
CAM1_TOPIC="${CAM1_TOPIC:-/cam1/image_raw}"
IMU_TOPIC="${IMU_TOPIC:-/imu0}"
CAMERA_MODEL_0="${CAMERA_MODEL_0:-pinhole-equi}"
CAMERA_MODEL_1="${CAMERA_MODEL_1:-pinhole-equi}"

IMU_UPDATE_RATE="${IMU_UPDATE_RATE:-200.0}"
IMU_ACCEL_NOISE_DENSITY="${IMU_ACCEL_NOISE_DENSITY:-0.01}"
IMU_ACCEL_RANDOM_WALK="${IMU_ACCEL_RANDOM_WALK:-0.001}"
IMU_GYRO_NOISE_DENSITY="${IMU_GYRO_NOISE_DENSITY:-0.001}"
IMU_GYRO_RANDOM_WALK="${IMU_GYRO_RANDOM_WALK:-0.0001}"

EXPECT_WIDTH="${EXPECT_WIDTH:-640}"
EXPECT_HEIGHT="${EXPECT_HEIGHT:-480}"
RECORD_PREFIX="${RECORD_PREFIX:-${CALIB_TARGET_NAME}_${EXPECT_WIDTH}x${EXPECT_HEIGHT}_calib}"
DATASET_GLOB="${DATASET_GLOB:-${RECORD_PREFIX}_*}"
BAG_PATTERN="${BAG_PATTERN:-${RECORD_PREFIX}_*.bag}"
CAMCHAIN_OUTPUT_NAME="${CAMCHAIN_OUTPUT_NAME:-camchain_${CALIB_PROFILE_NAME}.yaml}"
RESULTS_CAMERA_OUTPUT_NAME="${RESULTS_CAMERA_OUTPUT_NAME:-results-cam_${CALIB_PROFILE_NAME}.txt}"

export ROOT_PROJECT XR_CALIBRATION_ROOT XR_CALIB_COMMON_DIR XR_CALIB_COMMON_SCRIPT_DIR
export CALIB_TARGET TARGET_PROFILE CALIB_TARGET_NAME CALIB_LABEL CALIB_DEVICE_NAME CALIB_UNIT_ID CALIB_PROFILE_NAME
export CALIB_WORK_DIR RECORDS_DIR BAGS_DIR TARGETS_DIR KALIBR_RUNS_DIR CAMERA_PROFILE_DIR FINAL_PROFILE_DIR
export PACKAGE_ROOT CAPTURE_START_SCRIPT CAPTURE_CONFIG CAPTURE_CONFIG_CAMERA_ONLY CAPTURE_CONFIG_STEREO_IMU
export CONVERTER_TO_BAG CONVERTER_TO_RUNTIME RECORDER BASALT_VIO_CONFIG_TEMPLATE BASALT_VIO_CONFIG_NAME
export DOCKER_IMAGE ROS_SETUP APRILGRID_NAME APRILGRID_PATH
export IMU_YAML_NAME IMU_YAML_PATH CAM0_TOPIC CAM1_TOPIC IMU_TOPIC CAMERA_MODEL_0 CAMERA_MODEL_1
export IMU_UPDATE_RATE IMU_ACCEL_NOISE_DENSITY IMU_ACCEL_RANDOM_WALK IMU_GYRO_NOISE_DENSITY IMU_GYRO_RANDOM_WALK
export EXPECT_WIDTH EXPECT_HEIGHT RECORD_PREFIX DATASET_GLOB BAG_PATTERN CAMCHAIN_OUTPUT_NAME RESULTS_CAMERA_OUTPUT_NAME

print_target_summary() {
  cat <<SUMMARY
CALIB_TARGET=$CALIB_TARGET
CALIB_LABEL=$CALIB_LABEL
ROOT_PROJECT=$ROOT_PROJECT
PACKAGE_ROOT=$PACKAGE_ROOT
CALIB_WORK_DIR=$CALIB_WORK_DIR
RECORDS_DIR=$RECORDS_DIR
CALIB_PROFILE_NAME=$CALIB_PROFILE_NAME
CALIB_UNIT_ID=$CALIB_UNIT_ID
BASALT_VIO_CONFIG_NAME=$BASALT_VIO_CONFIG_NAME
EXPECT=${EXPECT_WIDTH}x${EXPECT_HEIGHT}
IMU_UPDATE_RATE=$IMU_UPDATE_RATE
CAPTURE_START_SCRIPT=$CAPTURE_START_SCRIPT
CAPTURE_CONFIG_CAMERA_ONLY=$CAPTURE_CONFIG_CAMERA_ONLY
CAPTURE_CONFIG_STEREO_IMU=$CAPTURE_CONFIG_STEREO_IMU
SUMMARY
}
